franq_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

from person import views as person_views
from garage import views as garage_views

urlpatterns = [
    path('', lambda req: redirect('/person/')),
    path('person/', include('person.urls')),
    path('person/', include('django.contrib.auth.urls')),
    path('garage/', include('garage.urls')),
    path('vehicle/', include('vehicle.urls')),
    path('thirdparty/clients', person_views.get_all_persons),
    path('thirdparty/garages', garage_views.list_active_garages),
    path('thirdparty/clientsgarage', person_views.get_parking_user_info),
    path('admin/', admin.site.urls),
]

garage/urls.py
from django.urls import path

from . import views

app_name = "garage"

urlpatterns = [
    path('', views.index, name='index'),
    path('available', views.available_list, name='available'),
]

person/urls.py
from django.urls import path

from . import views

app_name = "person"

urlpatterns = [
    path('', views.index, name='index'),
    path('update', views.update_person, name='update'),
    path('signup', views.signup_person, name='signup'),
]

vehicle/urls.py
from django.urls import path

from . import views

app_name = "vehicle"

urlpatterns = [
    path('<int:vehicle_id>/garage/add', views.add_to_garage, name='addgarage'),
    path('<int:vehicle_id>/garage/remove', views.remove_from_garage, name='removegarage'),
    path('<int:vehicle_id>/info', views.info, name='info'),
]

garage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Garage(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)

@receiver(post_save, sender=User)
def create_user_garage(sender, instance, created, **kwargs):
    if created:
        Garage.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_garage(sender, instance, **kwargs):
    instance.garage.save()

garage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from vehicle.models import Vehicle
from garage.models import Garage

import json

@login_required
def available_list(request):
    available_vehicles = Vehicle.available_vehicles()
    return render(request,'garage/available.html',{ 'available_vehicles': available_vehicles })

@login_required
def index(request):
    garage_vehicles = Vehicle.garage_vehicles(request.user.garage)
    return render(request,'garage/index.html',{ 'garage_vehicles': garage_vehicles })

#TODO: FT-32 - Add is_active field into Garage
def list_active_garages(request):
    response_data = []
    for garage in Garage.objects.all() :
        response_data.append({'garage_id':garage.id, 'user_fullname':garage.user.get_full_name()})
    return HttpResponse(json.dumps({ 'garages': response_data }), content_type="application/json")

garage/templates/garage/available.html
<h2> Available Vehicles </h2>
<a href="{% url 'garage:index' %}">My Garage</a>
<a href="{% url 'person:index' %}">My Config</a>
{% for vehicle in available_vehicles %}
<p>Vehicle: {{ vehicle.id }} </p>
<ul>
  <li>Model: {{ vehicle.model }}</li>
  <li>Type: {{ vehicle.v_type }}</li>
  <li>Brand: {{ vehicle.brand }}</li>
  <li>Color: {{ vehicle.color }}</li>
  <li>Manufactured year: {{ vehicle.manufactured_year }}</li>
</ul>
<a href="{% url 'vehicle:addgarage' vehicle.id %}">Add to garage</a>
{% endfor %}

garage/templates/garage/index.html
<h2>My Garage</h2>
<a href="{% url 'garage:available' %}">Available vehicles</a>
<a href="{% url 'person:index' %}">My Config</a>

{% for vehicle in garage_vehicles %}
<p>Vehicle: {{ vehicle.id }} </p>
<ul>
  <li>Model: {{ vehicle.model }}</li>
  <li>Type: {{ vehicle.v_type }}</li>
  <li>Brand: {{ vehicle.brand }}</li>
  <li>Color: {{ vehicle.color }}</li>
  <li>Manufactured year: {{ vehicle.manufactured_year }}</li>
</ul>
<a href="{% url 'vehicle:removegarage' vehicle.id %}">Remove from garage</a>
{% endfor %}